### ISSUE TITLE
Add a patron list subpage

### ISSUE THREAD

**Issue by sammyfung** [pyconhk/2017#30]

**Comment by tonyhhyip** [comment]
@sammyfung Please provide enough information for the issue

**Comment by sammyfung** [comment]
Dick Tang, Henry Law, Gregi Griffin, Lawrenece Law, Leon Chiu, Rossetti Huang.

**Comment by sammyfung** [comment]
Sorry for typos, please fix, thanks. :)
Gregi -> Greg
Lawrenece -> Lawrence

**Comment by railsstudent** [comment]
Fixed
